*** empty log message ***

diff --git a/trunk/test/Makefile.in b/trunk/test/Makefile.in
--- a/trunk/test/Makefile.in
+++ b/trunk/test/Makefile.in
@@ -20,7 +20,7 @@
 # See the file "COPYING" for information on usage and redistribution
 # of this file, and for a DISCLAIMER OF ALL WARRANTIES.
 #
-# @(#) $Id: Makefile.am,v 1.7 1999/06/06 07:40:36 strauss Exp $
+# @(#) $Id: Makefile.am,v 1.2 1999/06/07 15:44:07 strauss Exp $
 #
 
 
@@ -93,6 +93,9 @@ mibdir = @mibdir@
 smipath = @smipath@
 
 TESTMIBS = SNMPv2-MIB IF-MIB MAU-MIB
+
+TESTS = smilint.test smidump-1.test smidump-2.test
+TESTS_ENVIRONMENT = SMIPATH=@smipath@ TESTMIBS="$(TESTMIBS)"
 mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
 CONFIG_CLEAN_FILES = 
 DIST_COMMON =  Makefile.am Makefile.in
@@ -135,11 +138,37 @@ distdir: $(DISTFILES)
 	    || cp -p $$d/$$file $(distdir)/$$file || :; \
 	  fi; \
 	done
+check-TESTS: $(TESTS)
+	@failed=0; all=0; \
+	srcdir=$(srcdir); export srcdir; \
+	for tst in $(TESTS); do \
+	  if test -f $$tst; then dir=.; \
+	  else dir="$(srcdir)"; fi; \
+	  if $(TESTS_ENVIRONMENT) $$dir/$$tst; then \
+	    all=`expr $$all + 1`; \
+	    echo "PASS: $$tst"; \
+	  elif test $$? -ne 77; then \
+	    all=`expr $$all + 1`; \
+	    failed=`expr $$failed + 1`; \
+	    echo "FAIL: $$tst"; \
+	  fi; \
+	done; \
+	if test "$$failed" -eq 0; then \
+	  banner="All $$all tests passed"; \
+	else \
+	  banner="$$failed of $$all tests failed"; \
+	fi; \
+	dashes=`echo "$$banner" | sed s/./=/g`; \
+	echo "$$dashes"; \
+	echo "$$banner"; \
+	echo "$$dashes"; \
+	test "$$failed" -eq 0
 info-am:
 info: info-am
 dvi-am:
 dvi: dvi-am
 check-am: all-am
+	$(MAKE) $(AM_MAKEFLAGS) check-TESTS
 check: check-am
 installcheck-am:
 installcheck: installcheck-am
@@ -189,7 +218,7 @@ maintainer-clean-am:  maintainer-clean-generic distclean-am
 
 maintainer-clean: maintainer-clean-am
 
-.PHONY: tags distdir info-am info dvi-am dvi check check-am \
+.PHONY: tags distdir check-TESTS info-am info dvi-am dvi check check-am \
 installcheck-am installcheck install-exec-am install-exec \
 install-data-am install-data install-am install uninstall-am uninstall \
 all-redirect all-am all installdirs mostlyclean-generic \
@@ -197,38 +226,7 @@ distclean-generic clean-generic maintainer-clean-generic clean \
 mostlyclean distclean maintainer-clean
 
 
-test: test-smilint 
-
-test-smilint: .PHONY
-	-rm -rf test-smilint
-	mkdir test-smilint
-	SMIPATH=@smipath@ ; export SMIPATH
-	for mib in $(TESTMIBS) ; do \
-	    echo $$mib ; \
-	    ../tools/smilint -l9 $$mib > test-smilint/$$mib 2>&1 ; \
-	done
-	@echo ""
-	@echo "see directory test-smilint for results."
-
-test-smidump-smi-sming: .PHONY
-	-rm -rf test-smilint-smi-sming
-	mkdir test-smidump-smi-sming
-	SMIPATH=@smipath@ ; export SMIPATH
-	for mib in $(TESTMIBS) ; do \
-	    ../tools/smidump -fsming $$mib > test-smidump-smi-sming/$$mib 2>&1 ; \
-	done
-	@echo ""
-	@echo "see directory test-smidump-smi-sming for results."
-
-test-smidump-sming-sming: .PHONY
-	-rm -rf test-smilint-sming-sming
-	mkdir test-smidump-sming-sming
-	SMIPATH=@smipath@ ; export SMIPATH
-	for mib in $(TESTMIBS) ; do \
-	    ../tools/smidump -fsming $$mib > test-smidump-sming-sming/$$mib 2>&1 ; \
-	done
-	@echo ""
-	@echo "see directory test-smidump-sming-sming for results."
+#CLEANFILES		= smilint.out smidump-1.out smidump-2.out
 
 # Tell versions [3.59,3.63) of GNU make to not export all variables.
 # Otherwise a system limit (for SysV at least) may be exceeded.
